[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
dotenv = "0.15"
reqwest = { version = "0.12", features = ["blocking"] }
